#ifndef GUARD_CONSTANTS_POKEDEX_H
#define GUARD_CONSTANTS_POKEDEX_H

#define FOREACH_SPECIES_IN_NATIONAL_DEX_ORDER(F) \
    /* Kanto */ \
    F(BULBASAUR) \
    F(IVYSAUR) \
    F(VENUSAUR) \
    F(CHARMANDER) \
    F(CHARMELEON) \
    F(CHARIZARD) \
    F(SQUIRTLE) \
    F(WARTORTLE) \
    F(BLASTOISE) \
    F(CATERPIE) \
    F(METAPOD) \
    F(BUTTERFREE) \
    F(WEEDLE) \
    F(KAKUNA) \
    F(BEEDRILL) \
    F(PIDGEY) \
    F(PIDGEOTTO) \
    F(PIDGEOT) \
    F(RATTATA) \
    F(RATICATE) \
    F(SPEAROW) \
    F(FEAROW) \
    F(EKANS) \
    F(ARBOK) \
    F(PIKACHU) \
    F(RAICHU) \
    F(SANDSHREW) \
    F(SANDSLASH) \
    F(NIDORAN_F) \
    F(NIDORINA) \
    F(NIDOQUEEN) \
    F(NIDORAN_M) \
    F(NIDORINO) \
    F(NIDOKING) \
    F(CLEFAIRY) \
    F(CLEFABLE) \
    F(VULPIX) \
    F(NINETALES) \
    F(JIGGLYPUFF) \
    F(WIGGLYTUFF) \
    F(ZUBAT) \
    F(GOLBAT) \
    F(ODDISH) \
    F(GLOOM) \
    F(VILEPLUME) \
    F(PARAS) \
    F(PARASECT) \
    F(VENONAT) \
    F(VENOMOTH) \
    F(DIGLETT) \
    F(DUGTRIO) \
    F(MEOWTH) \
    F(PERSIAN) \
    F(PSYDUCK) \
    F(GOLDUCK) \
    F(MANKEY) \
    F(PRIMEAPE) \
    F(GROWLITHE) \
    F(ARCANINE) \
    F(POLIWAG) \
    F(POLIWHIRL) \
    F(POLIWRATH) \
    F(ABRA) \
    F(KADABRA) \
    F(ALAKAZAM) \
    F(MACHOP) \
    F(MACHOKE) \
    F(MACHAMP) \
    F(BELLSPROUT) \
    F(WEEPINBELL) \
    F(VICTREEBEL) \
    F(TENTACOOL) \
    F(TENTACRUEL) \
    F(GEODUDE) \
    F(GRAVELER) \
    F(GOLEM) \
    F(PONYTA) \
    F(RAPIDASH) \
    F(SLOWPOKE) \
    F(SLOWBRO) \
    F(MAGNEMITE) \
    F(MAGNETON) \
    F(FARFETCHD) \
    F(DODUO) \
    F(DODRIO) \
    F(SEEL) \
    F(DEWGONG) \
    F(GRIMER) \
    F(MUK) \
    F(SHELLDER) \
    F(CLOYSTER) \
    F(GASTLY) \
    F(HAUNTER) \
    F(GENGAR) \
    F(ONIX) \
    F(DROWZEE) \
    F(HYPNO) \
    F(KRABBY) \
    F(KINGLER) \
    F(VOLTORB) \
    F(ELECTRODE) \
    F(EXEGGCUTE) \
    F(EXEGGUTOR) \
    F(CUBONE) \
    F(MAROWAK) \
    F(HITMONLEE) \
    F(HITMONCHAN) \
    F(LICKITUNG) \
    F(KOFFING) \
    F(WEEZING) \
    F(RHYHORN) \
    F(RHYDON) \
    F(CHANSEY) \
    F(TANGELA) \
    F(KANGASKHAN) \
    F(HORSEA) \
    F(SEADRA) \
    F(GOLDEEN) \
    F(SEAKING) \
    F(STARYU) \
    F(STARMIE) \
    F(MR_MIME) \
    F(SCYTHER) \
    F(JYNX) \
    F(ELECTABUZZ) \
    F(MAGMAR) \
    F(PINSIR) \
    F(TAUROS) \
    F(MAGIKARP) \
    F(GYARADOS) \
    F(LAPRAS) \
    F(DITTO) \
    F(EEVEE) \
    F(VAPOREON) \
    F(JOLTEON) \
    F(FLAREON) \
    F(PORYGON) \
    F(OMANYTE) \
    F(OMASTAR) \
    F(KABUTO) \
    F(KABUTOPS) \
    F(AERODACTYL) \
    F(SNORLAX) \
    F(ARTICUNO) \
    F(ZAPDOS) \
    F(MOLTRES) \
    F(DRATINI) \
    F(DRAGONAIR) \
    F(DRAGONITE) \
    F(MEWTWO) \
    F(MEW) \
    /* Johto */ \
    F(CHIKORITA) \
    F(BAYLEEF) \
    F(MEGANIUM) \
    F(CYNDAQUIL) \
    F(QUILAVA) \
    F(TYPHLOSION) \
    F(TOTODILE) \
    F(CROCONAW) \
    F(FERALIGATR) \
    F(SENTRET) \
    F(FURRET) \
    F(HOOTHOOT) \
    F(NOCTOWL) \
    F(LEDYBA) \
    F(LEDIAN) \
    F(SPINARAK) \
    F(ARIADOS) \
    F(CROBAT) \
    F(CHINCHOU) \
    F(LANTURN) \
    F(PICHU) \
    F(CLEFFA) \
    F(IGGLYBUFF) \
    F(TOGEPI) \
    F(TOGETIC) \
    F(NATU) \
    F(XATU) \
    F(MAREEP) \
    F(FLAAFFY) \
    F(AMPHAROS) \
    F(BELLOSSOM) \
    F(MARILL) \
    F(AZUMARILL) \
    F(SUDOWOODO) \
    F(POLITOED) \
    F(HOPPIP) \
    F(SKIPLOOM) \
    F(JUMPLUFF) \
    F(AIPOM) \
    F(SUNKERN) \
    F(SUNFLORA) \
    F(YANMA) \
    F(WOOPER) \
    F(QUAGSIRE) \
    F(ESPEON) \
    F(UMBREON) \
    F(MURKROW) \
    F(SLOWKING) \
    F(MISDREAVUS) \
    F(UNOWN) \
    F(WOBBUFFET) \
    F(GIRAFARIG) \
    F(PINECO) \
    F(FORRETRESS) \
    F(DUNSPARCE) \
    F(GLIGAR) \
    F(STEELIX) \
    F(SNUBBULL) \
    F(GRANBULL) \
    F(QWILFISH) \
    F(SCIZOR) \
    F(SHUCKLE) \
    F(HERACROSS) \
    F(SNEASEL) \
    F(TEDDIURSA) \
    F(URSARING) \
    F(SLUGMA) \
    F(MAGCARGO) \
    F(SWINUB) \
    F(PILOSWINE) \
    F(CORSOLA) \
    F(REMORAID) \
    F(OCTILLERY) \
    F(DELIBIRD) \
    F(MANTINE) \
    F(SKARMORY) \
    F(HOUNDOUR) \
    F(HOUNDOOM) \
    F(KINGDRA) \
    F(PHANPY) \
    F(DONPHAN) \
    F(PORYGON2) \
    F(STANTLER) \
    F(SMEARGLE) \
    F(TYROGUE) \
    F(HITMONTOP) \
    F(SMOOCHUM) \
    F(ELEKID) \
    F(MAGBY) \
    F(MILTANK) \
    F(BLISSEY) \
    F(RAIKOU) \
    F(ENTEI) \
    F(SUICUNE) \
    F(LARVITAR) \
    F(PUPITAR) \
    F(TYRANITAR) \
    F(LUGIA) \
    F(HO_OH) \
    F(CELEBI) \
    /* Hoenn */ \
    F(TREECKO) \
    F(GROVYLE) \
    F(SCEPTILE) \
    F(TORCHIC) \
    F(COMBUSKEN) \
    F(BLAZIKEN) \
    F(MUDKIP) \
    F(MARSHTOMP) \
    F(SWAMPERT) \
    F(POOCHYENA) \
    F(MIGHTYENA) \
    F(ZIGZAGOON) \
    F(LINOONE) \
    F(WURMPLE) \
    F(SILCOON) \
    F(BEAUTIFLY) \
    F(CASCOON) \
    F(DUSTOX) \
    F(LOTAD) \
    F(LOMBRE) \
    F(LUDICOLO) \
    F(SEEDOT) \
    F(NUZLEAF) \
    F(SHIFTRY) \
    F(TAILLOW) \
    F(SWELLOW) \
    F(WINGULL) \
    F(PELIPPER) \
    F(RALTS) \
    F(KIRLIA) \
    F(GARDEVOIR) \
    F(SURSKIT) \
    F(MASQUERAIN) \
    F(SHROOMISH) \
    F(BRELOOM) \
    F(SLAKOTH) \
    F(VIGOROTH) \
    F(SLAKING) \
    F(NINCADA) \
    F(NINJASK) \
    F(SHEDINJA) \
    F(WHISMUR) \
    F(LOUDRED) \
    F(EXPLOUD) \
    F(MAKUHITA) \
    F(HARIYAMA) \
    F(AZURILL) \
    F(NOSEPASS) \
    F(SKITTY) \
    F(DELCATTY) \
    F(SABLEYE) \
    F(MAWILE) \
    F(ARON) \
    F(LAIRON) \
    F(AGGRON) \
    F(MEDITITE) \
    F(MEDICHAM) \
    F(ELECTRIKE) \
    F(MANECTRIC) \
    F(PLUSLE) \
    F(MINUN) \
    F(VOLBEAT) \
    F(ILLUMISE) \
    F(ROSELIA) \
    F(GULPIN) \
    F(SWALOT) \
    F(CARVANHA) \
    F(SHARPEDO) \
    F(WAILMER) \
    F(WAILORD) \
    F(NUMEL) \
    F(CAMERUPT) \
    F(TORKOAL) \
    F(SPOINK) \
    F(GRUMPIG) \
    F(SPINDA) \
    F(TRAPINCH) \
    F(VIBRAVA) \
    F(FLYGON) \
    F(CACNEA) \
    F(CACTURNE) \
    F(SWABLU) \
    F(ALTARIA) \
    F(ZANGOOSE) \
    F(SEVIPER) \
    F(LUNATONE) \
    F(SOLROCK) \
    F(BARBOACH) \
    F(WHISCASH) \
    F(CORPHISH) \
    F(CRAWDAUNT) \
    F(BALTOY) \
    F(CLAYDOL) \
    F(LILEEP) \
    F(CRADILY) \
    F(ANORITH) \
    F(ARMALDO) \
    F(FEEBAS) \
    F(MILOTIC) \
    F(CASTFORM) \
    F(KECLEON) \
    F(SHUPPET) \
    F(BANETTE) \
    F(DUSKULL) \
    F(DUSCLOPS) \
    F(TROPIUS) \
    F(CHIMECHO) \
    F(ABSOL) \
    F(WYNAUT) \
    F(SNORUNT) \
    F(GLALIE) \
    F(SPHEAL) \
    F(SEALEO) \
    F(WALREIN) \
    F(CLAMPERL) \
    F(HUNTAIL) \
    F(GOREBYSS) \
    F(RELICANTH) \
    F(LUVDISC) \
    F(BAGON) \
    F(SHELGON) \
    F(SALAMENCE) \
    F(BELDUM) \
    F(METANG) \
    F(METAGROSS) \
    F(REGIROCK) \
    F(REGICE) \
    F(REGISTEEL) \
    F(LATIAS) \
    F(LATIOS) \
    F(KYOGRE) \
    F(GROUDON) \
    F(RAYQUAZA) \
    F(JIRACHI) \
    F(DEOXYS) \
    /* Old Unown */ \
    F(OLD_UNOWN_B) \
    F(OLD_UNOWN_C) \
    F(OLD_UNOWN_D) \
    F(OLD_UNOWN_E) \
    F(OLD_UNOWN_F) \
    F(OLD_UNOWN_G) \
    F(OLD_UNOWN_H) \
    F(OLD_UNOWN_I) \
    F(OLD_UNOWN_J) \
    F(OLD_UNOWN_K) \
    F(OLD_UNOWN_L) \
    F(OLD_UNOWN_M) \
    F(OLD_UNOWN_N) \
    F(OLD_UNOWN_O) \
    F(OLD_UNOWN_P) \
    F(OLD_UNOWN_Q) \
    F(OLD_UNOWN_R) \
    F(OLD_UNOWN_S) \
    F(OLD_UNOWN_T) \
    F(OLD_UNOWN_U) \
    F(OLD_UNOWN_V) \
    F(OLD_UNOWN_W) \
    F(OLD_UNOWN_X) \
    F(OLD_UNOWN_Y) \
    F(OLD_UNOWN_Z) \

// National Pokédex order
enum {
    NATIONAL_DEX_NONE,
    #define NATIONAL_DEX_ENUM(name) NATIONAL_DEX_ ## name,
    FOREACH_SPECIES_IN_NATIONAL_DEX_ORDER(NATIONAL_DEX_ENUM)
    #undef NATIONAL_DEX_ENUM
};

#define KANTO_DEX_COUNT     NATIONAL_DEX_MEW
#define JOHTO_DEX_COUNT     NATIONAL_DEX_CELEBI
#define NATIONAL_DEX_COUNT  NATIONAL_DEX_DEOXYS

// Hoenn Pokédex order
enum {
    HOENN_DEX_NONE,
    HOENN_DEX_TREECKO,
    HOENN_DEX_GROVYLE,
    HOENN_DEX_SCEPTILE,
    HOENN_DEX_TORCHIC,
    HOENN_DEX_COMBUSKEN,
    HOENN_DEX_BLAZIKEN,
    HOENN_DEX_MUDKIP,
    HOENN_DEX_MARSHTOMP,
    HOENN_DEX_SWAMPERT,
    HOENN_DEX_POOCHYENA,
    HOENN_DEX_MIGHTYENA,
    HOENN_DEX_ZIGZAGOON,
    HOENN_DEX_LINOONE,
    HOENN_DEX_WURMPLE,
    HOENN_DEX_SILCOON,
    HOENN_DEX_BEAUTIFLY,
    HOENN_DEX_CASCOON,
    HOENN_DEX_DUSTOX,
    HOENN_DEX_LOTAD,
    HOENN_DEX_LOMBRE,
    HOENN_DEX_LUDICOLO,
    HOENN_DEX_SEEDOT,
    HOENN_DEX_NUZLEAF,
    HOENN_DEX_SHIFTRY,
    HOENN_DEX_TAILLOW,
    HOENN_DEX_SWELLOW,
    HOENN_DEX_WINGULL,
    HOENN_DEX_PELIPPER,
    HOENN_DEX_RALTS,
    HOENN_DEX_KIRLIA,
    HOENN_DEX_GARDEVOIR,
    HOENN_DEX_SURSKIT,
    HOENN_DEX_MASQUERAIN,
    HOENN_DEX_SHROOMISH,
    HOENN_DEX_BRELOOM,
    HOENN_DEX_SLAKOTH,
    HOENN_DEX_VIGOROTH,
    HOENN_DEX_SLAKING,
    HOENN_DEX_ABRA,
    HOENN_DEX_KADABRA,
    HOENN_DEX_ALAKAZAM,
    HOENN_DEX_NINCADA,
    HOENN_DEX_NINJASK,
    HOENN_DEX_SHEDINJA,
    HOENN_DEX_WHISMUR,
    HOENN_DEX_LOUDRED,
    HOENN_DEX_EXPLOUD,
    HOENN_DEX_MAKUHITA,
    HOENN_DEX_HARIYAMA,
    HOENN_DEX_GOLDEEN,
    HOENN_DEX_SEAKING,
    HOENN_DEX_MAGIKARP,
    HOENN_DEX_GYARADOS,
    HOENN_DEX_AZURILL,
    HOENN_DEX_MARILL,
    HOENN_DEX_AZUMARILL,
    HOENN_DEX_GEODUDE,
    HOENN_DEX_GRAVELER,
    HOENN_DEX_GOLEM,
    HOENN_DEX_NOSEPASS,
    HOENN_DEX_SKITTY,
    HOENN_DEX_DELCATTY,
    HOENN_DEX_ZUBAT,
    HOENN_DEX_GOLBAT,
    HOENN_DEX_CROBAT,
    HOENN_DEX_TENTACOOL,
    HOENN_DEX_TENTACRUEL,
    HOENN_DEX_SABLEYE,
    HOENN_DEX_MAWILE,
    HOENN_DEX_ARON,
    HOENN_DEX_LAIRON,
    HOENN_DEX_AGGRON,
    HOENN_DEX_MACHOP,
    HOENN_DEX_MACHOKE,
    HOENN_DEX_MACHAMP,
    HOENN_DEX_MEDITITE,
    HOENN_DEX_MEDICHAM,
    HOENN_DEX_ELECTRIKE,
    HOENN_DEX_MANECTRIC,
    HOENN_DEX_PLUSLE,
    HOENN_DEX_MINUN,
    HOENN_DEX_MAGNEMITE,
    HOENN_DEX_MAGNETON,
    HOENN_DEX_VOLTORB,
    HOENN_DEX_ELECTRODE,
    HOENN_DEX_VOLBEAT,
    HOENN_DEX_ILLUMISE,
    HOENN_DEX_ODDISH,
    HOENN_DEX_GLOOM,
    HOENN_DEX_VILEPLUME,
    HOENN_DEX_BELLOSSOM,
    HOENN_DEX_DODUO,
    HOENN_DEX_DODRIO,
    HOENN_DEX_ROSELIA,
    HOENN_DEX_GULPIN,
    HOENN_DEX_SWALOT,
    HOENN_DEX_CARVANHA,
    HOENN_DEX_SHARPEDO,
    HOENN_DEX_WAILMER,
    HOENN_DEX_WAILORD,
    HOENN_DEX_NUMEL,
    HOENN_DEX_CAMERUPT,
    HOENN_DEX_SLUGMA,
    HOENN_DEX_MAGCARGO,
    HOENN_DEX_TORKOAL,
    HOENN_DEX_GRIMER,
    HOENN_DEX_MUK,
    HOENN_DEX_KOFFING,
    HOENN_DEX_WEEZING,
    HOENN_DEX_SPOINK,
    HOENN_DEX_GRUMPIG,
    HOENN_DEX_SANDSHREW,
    HOENN_DEX_SANDSLASH,
    HOENN_DEX_SPINDA,
    HOENN_DEX_SKARMORY,
    HOENN_DEX_TRAPINCH,
    HOENN_DEX_VIBRAVA,
    HOENN_DEX_FLYGON,
    HOENN_DEX_CACNEA,
    HOENN_DEX_CACTURNE,
    HOENN_DEX_SWABLU,
    HOENN_DEX_ALTARIA,
    HOENN_DEX_ZANGOOSE,
    HOENN_DEX_SEVIPER,
    HOENN_DEX_LUNATONE,
    HOENN_DEX_SOLROCK,
    HOENN_DEX_BARBOACH,
    HOENN_DEX_WHISCASH,
    HOENN_DEX_CORPHISH,
    HOENN_DEX_CRAWDAUNT,
    HOENN_DEX_BALTOY,
    HOENN_DEX_CLAYDOL,
    HOENN_DEX_LILEEP,
    HOENN_DEX_CRADILY,
    HOENN_DEX_ANORITH,
    HOENN_DEX_ARMALDO,
    HOENN_DEX_IGGLYBUFF,
    HOENN_DEX_JIGGLYPUFF,
    HOENN_DEX_WIGGLYTUFF,
    HOENN_DEX_FEEBAS,
    HOENN_DEX_MILOTIC,
    HOENN_DEX_CASTFORM,
    HOENN_DEX_STARYU,
    HOENN_DEX_STARMIE,
    HOENN_DEX_KECLEON,
    HOENN_DEX_SHUPPET,
    HOENN_DEX_BANETTE,
    HOENN_DEX_DUSKULL,
    HOENN_DEX_DUSCLOPS,
    HOENN_DEX_TROPIUS,
    HOENN_DEX_CHIMECHO,
    HOENN_DEX_ABSOL,
    HOENN_DEX_VULPIX,
    HOENN_DEX_NINETALES,
    HOENN_DEX_PICHU,
    HOENN_DEX_PIKACHU,
    HOENN_DEX_RAICHU,
    HOENN_DEX_PSYDUCK,
    HOENN_DEX_GOLDUCK,
    HOENN_DEX_WYNAUT,
    HOENN_DEX_WOBBUFFET,
    HOENN_DEX_NATU,
    HOENN_DEX_XATU,
    HOENN_DEX_GIRAFARIG,
    HOENN_DEX_PHANPY,
    HOENN_DEX_DONPHAN,
    HOENN_DEX_PINSIR,
    HOENN_DEX_HERACROSS,
    HOENN_DEX_RHYHORN,
    HOENN_DEX_RHYDON,
    HOENN_DEX_SNORUNT,
    HOENN_DEX_GLALIE,
    HOENN_DEX_SPHEAL,
    HOENN_DEX_SEALEO,
    HOENN_DEX_WALREIN,
    HOENN_DEX_CLAMPERL,
    HOENN_DEX_HUNTAIL,
    HOENN_DEX_GOREBYSS,
    HOENN_DEX_RELICANTH,
    HOENN_DEX_CORSOLA,
    HOENN_DEX_CHINCHOU,
    HOENN_DEX_LANTURN,
    HOENN_DEX_LUVDISC,
    HOENN_DEX_HORSEA,
    HOENN_DEX_SEADRA,
    HOENN_DEX_KINGDRA,
    HOENN_DEX_BAGON,
    HOENN_DEX_SHELGON,
    HOENN_DEX_SALAMENCE,
    HOENN_DEX_BELDUM,
    HOENN_DEX_METANG,
    HOENN_DEX_METAGROSS,
    HOENN_DEX_REGIROCK,
    HOENN_DEX_REGICE,
    HOENN_DEX_REGISTEEL,
    HOENN_DEX_LATIAS,
    HOENN_DEX_LATIOS,
    HOENN_DEX_KYOGRE,
    HOENN_DEX_GROUDON,
    HOENN_DEX_RAYQUAZA,
    HOENN_DEX_JIRACHI,
    HOENN_DEX_DEOXYS,
    // End of Hoenn Dex (see HOENN_DEX_COUNT)
    // Here below have values but are excluded from the Pokédex
    HOENN_DEX_BULBASAUR,
    HOENN_DEX_IVYSAUR,
    HOENN_DEX_VENUSAUR,
    HOENN_DEX_CHARMANDER,
    HOENN_DEX_CHARMELEON,
    HOENN_DEX_CHARIZARD,
    HOENN_DEX_SQUIRTLE,
    HOENN_DEX_WARTORTLE,
    HOENN_DEX_BLASTOISE,
    HOENN_DEX_CATERPIE,
    HOENN_DEX_METAPOD,
    HOENN_DEX_BUTTERFREE,
    HOENN_DEX_WEEDLE,
    HOENN_DEX_KAKUNA,
    HOENN_DEX_BEEDRILL,
    HOENN_DEX_PIDGEY,
    HOENN_DEX_PIDGEOTTO,
    HOENN_DEX_PIDGEOT,
    HOENN_DEX_RATTATA,
    HOENN_DEX_RATICATE,
    HOENN_DEX_SPEAROW,
    HOENN_DEX_FEAROW,
    HOENN_DEX_EKANS,
    HOENN_DEX_ARBOK,
    HOENN_DEX_NIDORAN_F,
    HOENN_DEX_NIDORINA,
    HOENN_DEX_NIDOQUEEN,
    HOENN_DEX_NIDORAN_M,
    HOENN_DEX_NIDORINO,
    HOENN_DEX_NIDOKING,
    HOENN_DEX_CLEFAIRY,
    HOENN_DEX_CLEFABLE,
    HOENN_DEX_PARAS,
    HOENN_DEX_PARASECT,
    HOENN_DEX_VENONAT,
    HOENN_DEX_VENOMOTH,
    HOENN_DEX_DIGLETT,
    HOENN_DEX_DUGTRIO,
    HOENN_DEX_MEOWTH,
    HOENN_DEX_PERSIAN,
    HOENN_DEX_MANKEY,
    HOENN_DEX_PRIMEAPE,
    HOENN_DEX_GROWLITHE,
    HOENN_DEX_ARCANINE,
    HOENN_DEX_POLIWAG,
    HOENN_DEX_POLIWHIRL,
    HOENN_DEX_POLIWRATH,
    HOENN_DEX_BELLSPROUT,
    HOENN_DEX_WEEPINBELL,
    HOENN_DEX_VICTREEBEL,
    HOENN_DEX_PONYTA,
    HOENN_DEX_RAPIDASH,
    HOENN_DEX_SLOWPOKE,
    HOENN_DEX_SLOWBRO,
    HOENN_DEX_FARFETCHD,
    HOENN_DEX_SEEL,
    HOENN_DEX_DEWGONG,
    HOENN_DEX_SHELLDER,
    HOENN_DEX_CLOYSTER,
    HOENN_DEX_GASTLY,
    HOENN_DEX_HAUNTER,
    HOENN_DEX_GENGAR,
    HOENN_DEX_ONIX,
    HOENN_DEX_DROWZEE,
    HOENN_DEX_HYPNO,
    HOENN_DEX_KRABBY,
    HOENN_DEX_KINGLER,
    HOENN_DEX_EXEGGCUTE,
    HOENN_DEX_EXEGGUTOR,
    HOENN_DEX_CUBONE,
    HOENN_DEX_MAROWAK,
    HOENN_DEX_HITMONLEE,
    HOENN_DEX_HITMONCHAN,
    HOENN_DEX_LICKITUNG,
    HOENN_DEX_CHANSEY,
    HOENN_DEX_TANGELA,
    HOENN_DEX_KANGASKHAN,
    HOENN_DEX_MR_MIME,
    HOENN_DEX_SCYTHER,
    HOENN_DEX_JYNX,
    HOENN_DEX_ELECTABUZZ,
    HOENN_DEX_MAGMAR,
    HOENN_DEX_TAUROS,
    HOENN_DEX_LAPRAS,
    HOENN_DEX_DITTO,
    HOENN_DEX_EEVEE,
    HOENN_DEX_VAPOREON,
    HOENN_DEX_JOLTEON,
    HOENN_DEX_FLAREON,
    HOENN_DEX_PORYGON,
    HOENN_DEX_OMANYTE,
    HOENN_DEX_OMASTAR,
    HOENN_DEX_KABUTO,
    HOENN_DEX_KABUTOPS,
    HOENN_DEX_AERODACTYL,
    HOENN_DEX_SNORLAX,
    HOENN_DEX_ARTICUNO,
    HOENN_DEX_ZAPDOS,
    HOENN_DEX_MOLTRES,
    HOENN_DEX_DRATINI,
    HOENN_DEX_DRAGONAIR,
    HOENN_DEX_DRAGONITE,
    HOENN_DEX_MEWTWO,
    HOENN_DEX_MEW,
    HOENN_DEX_CHIKORITA,
    HOENN_DEX_BAYLEEF,
    HOENN_DEX_MEGANIUM,
    HOENN_DEX_CYNDAQUIL,
    HOENN_DEX_QUILAVA,
    HOENN_DEX_TYPHLOSION,
    HOENN_DEX_TOTODILE,
    HOENN_DEX_CROCONAW,
    HOENN_DEX_FERALIGATR,
    HOENN_DEX_SENTRET,
    HOENN_DEX_FURRET,
    HOENN_DEX_HOOTHOOT,
    HOENN_DEX_NOCTOWL,
    HOENN_DEX_LEDYBA,
    HOENN_DEX_LEDIAN,
    HOENN_DEX_SPINARAK,
    HOENN_DEX_ARIADOS,
    HOENN_DEX_CLEFFA,
    HOENN_DEX_TOGEPI,
    HOENN_DEX_TOGETIC,
    HOENN_DEX_MAREEP,
    HOENN_DEX_FLAAFFY,
    HOENN_DEX_AMPHAROS,
    HOENN_DEX_SUDOWOODO,
    HOENN_DEX_POLITOED,
    HOENN_DEX_HOPPIP,
    HOENN_DEX_SKIPLOOM,
    HOENN_DEX_JUMPLUFF,
    HOENN_DEX_AIPOM,
    HOENN_DEX_SUNKERN,
    HOENN_DEX_SUNFLORA,
    HOENN_DEX_YANMA,
    HOENN_DEX_WOOPER,
    HOENN_DEX_QUAGSIRE,
    HOENN_DEX_ESPEON,
    HOENN_DEX_UMBREON,
    HOENN_DEX_MURKROW,
    HOENN_DEX_SLOWKING,
    HOENN_DEX_MISDREAVUS,
    HOENN_DEX_UNOWN,
    HOENN_DEX_PINECO,
    HOENN_DEX_FORRETRESS,
    HOENN_DEX_DUNSPARCE,
    HOENN_DEX_GLIGAR,
    HOENN_DEX_STEELIX,
    HOENN_DEX_SNUBBULL,
    HOENN_DEX_GRANBULL,
    HOENN_DEX_QWILFISH,
    HOENN_DEX_SCIZOR,
    HOENN_DEX_SHUCKLE,
    HOENN_DEX_SNEASEL,
    HOENN_DEX_TEDDIURSA,
    HOENN_DEX_URSARING,
    HOENN_DEX_SWINUB,
    HOENN_DEX_PILOSWINE,
    HOENN_DEX_REMORAID,
    HOENN_DEX_OCTILLERY,
    HOENN_DEX_DELIBIRD,
    HOENN_DEX_MANTINE,
    HOENN_DEX_HOUNDOUR,
    HOENN_DEX_HOUNDOOM,
    HOENN_DEX_PORYGON2,
    HOENN_DEX_STANTLER,
    HOENN_DEX_SMEARGLE,
    HOENN_DEX_TYROGUE,
    HOENN_DEX_HITMONTOP,
    HOENN_DEX_SMOOCHUM,
    HOENN_DEX_ELEKID,
    HOENN_DEX_MAGBY,
    HOENN_DEX_MILTANK,
    HOENN_DEX_BLISSEY,
    HOENN_DEX_RAIKOU,
    HOENN_DEX_ENTEI,
    HOENN_DEX_SUICUNE,
    HOENN_DEX_LARVITAR,
    HOENN_DEX_PUPITAR,
    HOENN_DEX_TYRANITAR,
    HOENN_DEX_LUGIA,
    HOENN_DEX_HO_OH,
    HOENN_DEX_CELEBI,
    HOENN_DEX_OLD_UNOWN_B,
    HOENN_DEX_OLD_UNOWN_C,
    HOENN_DEX_OLD_UNOWN_D,
    HOENN_DEX_OLD_UNOWN_E,
    HOENN_DEX_OLD_UNOWN_F,
    HOENN_DEX_OLD_UNOWN_G,
    HOENN_DEX_OLD_UNOWN_H,
    HOENN_DEX_OLD_UNOWN_I,
    HOENN_DEX_OLD_UNOWN_J,
    HOENN_DEX_OLD_UNOWN_K,
    HOENN_DEX_OLD_UNOWN_L,
    HOENN_DEX_OLD_UNOWN_M,
    HOENN_DEX_OLD_UNOWN_N,
    HOENN_DEX_OLD_UNOWN_O,
    HOENN_DEX_OLD_UNOWN_P,
    HOENN_DEX_OLD_UNOWN_Q,
    HOENN_DEX_OLD_UNOWN_R,
    HOENN_DEX_OLD_UNOWN_S,
    HOENN_DEX_OLD_UNOWN_T,
    HOENN_DEX_OLD_UNOWN_U,
    HOENN_DEX_OLD_UNOWN_V,
    HOENN_DEX_OLD_UNOWN_W,
    HOENN_DEX_OLD_UNOWN_X,
    HOENN_DEX_OLD_UNOWN_Y,
    HOENN_DEX_OLD_UNOWN_Z,
};

#define HOENN_DEX_COUNT HOENN_DEX_DEOXYS

#endif // GUARD_CONSTANTS_POKEDEX_H
