#ifndef GUARD_CONSTANTS_TEST_RUNNER_H
#define GUARD_CONSTANTS_TEST_RUNNER_H

enum MenuInputType
{
    MENU_INPUT_NONE,
    MENU_INPUT_MENU,
    MENU_INPUT_GRIDMENU,
    MENU_INPUT_LISTMENU,
    MENU_INPUT_QUANTITY,
};

#endif
