// This file is included via -imacro for a second pass through cpp after
// running preproc. It is useful for defining macros that are referenced
// in the code generated by preproc.
#include "data.h"
#include "gba/defines.h"
#include "constants/abilities.h"
#include "constants/items.h"
#include "constants/moves.h"
#include "constants/pokemon.h"
#include "constants/species.h"
#include "constants/trainers.h"
